### ISSUE TITLE
您好，请问能否支持鼠标滚轮？mouseWheel属性

### ISSUE THREAD

**Issue by ChinaBigPan** [soluteli/rc-bscroll#3]
better-scroll版本在1.8.0之后支持了这一属性。

**Comment by soluteli** [comment]
**测试环境**
- better-scroll v1.21.1

**平台**
- chrome v66.0.3359.139


**调试结果**
![](http://pakln1e7m.bkt.clouddn.com/issue/issue3.png)
现象：
- pc 端已如 [better-scroll 文档](https://ustbhuangyi.github.io/better-scroll/doc/zh-hans/options.html#disablemouse) 自动设置 `disableMouse： false`
- 不响应 mouseWheel 事件

**结论**
1. 需要先验证 better-scroll 对 MouseWheel 支持与否
2. 因为项目主要针对移动端，所以暂无计划支持 MouseWheel
